import { execSync } from 'child_process';
import inquirer from 'inquirer';
import fs from 'fs-extra';
import path from 'path';
import os from 'os';
import { logger } from './logger.js';

export interface GenerateCommitMessageOptions {
  worktreePath: string;
  timeout?: number;
}

export interface CommitMessageResult {
  success: boolean;
  message: string;
  fallbackUsed: boolean;
  error?: string;
}

async function promptForCommitMessage(): Promise<string> {
  try {
    const answers = await inquirer.prompt([
      {
        type: 'input',
        name: 'commitMessage',
        message: 'Enter commit message:',
        validate: (input: string) => {
          if (!input || input.trim() === '') {
            return 'Commit message cannot be empty';
          }
          return true;
        }
      }
    ]);
    return answers.commitMessage.trim();
  } catch (error) {
    // Fallback if prompt fails (no TTY)
    const timestamp = new Date().toISOString();
    return `claude-sandbox: automatic commit [${timestamp}]`;
  }
}

async function promptForCommitMethod(): Promise<'manual' | 'ai'> {
  try {
    const answers = await inquirer.prompt([
      {
        type: 'expand',
        name: 'method',
        message: 'How would you like to create the commit message?',
        default: 'a',
        choices: [
          { key: 'a', name: 'Generate with AI (includes conversation context)', value: 'ai' },
          { key: 'm', name: 'Write it myself', value: 'manual' }
        ]
      }
    ]);
    return answers.method;
  } catch (error) {
    // Fallback to AI if prompt fails
    return 'ai';
  }
}

export async function generateCommitMessage(
  options: GenerateCommitMessageOptions
): Promise<CommitMessageResult> {
  const { worktreePath, timeout = 30000 } = options;

  // Ask user which method to use
  const method = await promptForCommitMethod();

  if (method === 'manual') {
    logger.info('Enter your commit message:');
    const userMessage = await promptForCommitMessage();
    return {
      success: false,
      message: userMessage,
      fallbackUsed: true
    };
  }

  // AI generation
  logger.debug('Loading conversation context for better commit message...');


  let prompt = `Stage all changes with 'git add -A', then create an appropriate commit message based on the changes.

Feel free to use git commands (git diff, git status, git log, etc.) to examine the changes and context before generating the commit message.

Requirements:
- Follow conventional commit format (type: description)
- Be concise but descriptive
- Use present tense ("add" not "added")
- Limit first line to 72 characters
- This is from a Claude Code sandbox session

IMPORTANT: Do NOT include any information in the commit message about it being generated by Claude Code, AI, or give any credit to Claude. The commit message should be a standard, professional git commit message with no meta-commentary about its origin.

After generating the message, run 'git commit' with that message. Use 'git commit -m "message"' format.`;

  try {
    logger.info('Creating commit with Claude Code...');

    // Run claude with inherited stdio to show thinking/tokens in real-time
    execSync(
      `claude -p ${JSON.stringify(prompt)} --allowed-tools "Read,Glob,Grep,Bash(git add:*),Bash(git commit:*),Bash(git diff:*),Bash(git log:*),Bash(git status:*),Bash(ls:*),Bash(find:*)"`,
      {
        cwd: worktreePath,
        stdio: 'inherit',
        timeout
      }
    );

    // If we get here, Claude succeeded
    const message = 'Commit created by Claude Code';

    logger.debug(`Commit created successfully`);

    return {
      success: true,
      message,
      fallbackUsed: false
    };
  } catch (error) {
    logger.warn(`AI commit failed: ${(error as Error).message}`);
    logger.info('Please provide a commit message:');

    // Prompt user for commit message as fallback
    const userMessage = await promptForCommitMessage();

    return {
      success: false,
      message: userMessage,
      fallbackUsed: true,
      error: (error as Error).message
    };
  }
}
